language: cpp
os: osx
env:
  global:
    - GOARCH=amd64
    - GO_VERSION=1.7.1
  matrix:
    - GOOS=linux
    - GOOS=darwin
    - GOOS=freebsd
    - GOOS=windows
    - GOOS=openbsd
    - GOOS=netbsd
branches:
  only:
  - master
install: ./.travis/install-go.sh
script: ./.travis/build.sh
cache:
  directories:
  - $HOME/go$GO_VERSION
  - $HOME/gobootstrap$GO_VERSION
